# Generated by Django 5.1.4 on 2025-01-06 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('swim', 'Swimming'), ('bike', 'Cycling'), ('run', 'Running')], max_length=10)),
                ('distance_m', models.IntegerField(help_text='Distance in meters')),
                ('duration', models.DurationField(help_text='Duration of the workout (hh:mm:ss)')),
                ('date', models.DateField(help_text='Date of the workout')),
                ('intensity', models.PositiveSmallIntegerField(help_text='Intensity of the workout on a scale from 1 to 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the workout', null=True)),
            ],
        ),
    ]
