# Generated by Django 5.1.4 on 2025-01-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_logs', '0002_workout_name_alter_workout_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], help_text='Intensity of the workout on a scale from 1 - 5'),
        ),
    ]
