# Generated by Django 5.1.4 on 2025-01-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_race'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['date']},
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('swim', 'Swim'), ('ride', 'Ride'), ('run', 'Run')], help_text='Select the type of discipline', max_length=10)),
                ('distance', models.IntegerField(help_text='Distance in meters')),
                ('time_limit', models.DurationField(blank=True, help_text='Optional time limit for the discipline', null=True)),
                ('order', models.PositiveIntegerField(help_text='Order of the discipline in the race')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='workout_logs.race')),
            ],
        ),
    ]
