# Generated by Django 5.1.4 on 2025-03-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_workout_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Order of the discipline in the race', null=True),
        ),
    ]
