# Generated by Django 5.1.4 on 2025-03-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_discipline_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='race_name',
            new_name='name',
        ),
    ]
