# Generated by Django 5.1.4 on 2025-01-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, help_text='Name or title of the workout', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='activity_type',
            field=models.CharField(choices=[('swim', 'Swim'), ('bike', 'Ride'), ('run', 'Run')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], help_text='Intensity of the workout on a scale from 1 to 10'),
        ),
    ]
