# Generated by Django 5.1.4 on 2025-01-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_logs', '0003_alter_workout_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='activity_type',
            field=models.CharField(choices=[('swim', 'Swim'), ('ride', 'Ride'), ('run', 'Run')], max_length=10),
        ),
    ]
